### ISSUE TITLE
Question on motion model for drones

### ISSUE THREAD

**Issue by agnivade** [milosgajdos83/go-estimate#2]
Hi,

We are looking for an UKF for motion modelling a drone path where degrees of freedom are very high. Just wanted to check this library is generic enough to incorporate any complex motion model.

**Comment by milosgajdos83** [comment]
Hi

> wanted to check this library is generic enough

Is a generic question :-) It depends on the actual usecase but the library has been designed to be as generic as I could think of; fundamentally it's very simple - all interfaces are defined in `filter.go` and actual filter implementations are in particular filter `Go` packages.

I'm not sure if this answers your question, but I guess if you can be more specific I might be able to provide better answer.

**Comment by agnivade** [comment]
Great, thank you !
